### PR TITLE
Code migration

### PR DESCRIPTION
**Pull request by parunagiri**
Hi @balaganeshbc ,
Pulling out all bug fixes from redbull to Mass base code. Please review and let me know your thoughts

### CODE REVIEW

**Review by backer — COMMENTED** [review]
Just confirming that MaaS will have custom features that won't be merged into the base wrapper? Also that they do not have the custom red bull only features?

**Comment by parunagiri** [comment]
> Also that they do not have the custom red bull only features?

**Comment by parunagiri** [comment]
> Just confirming that MaaS will have custom features that won't be merged into the base wrapper? Also that they do not have the custom red bull only features?

Yes, @backer. The Maas custom features will not be merged into the base wrapper, but we can adopt certain play-controls features to the base wrapper. Those are Audio mute/unmute and rotate the screen. 

the Redbull-only features will be removed from the Maas repo.

**Comment by backer** [comment]
@parunagiri thanks for your answer. In that case, does it make more sense to add the new general features to the base wrapper repo and then fork that for MaaS

**Comment by parunagiri** [comment]
> @parunagiri thanks for your answer. In that case, does it make more sense to add the new general features to the base wrapper repo and then fork that for MaaS

Sure

**Review by balaganeshbc — APPROVED** [review]

**Pull request merged**
